/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package image.text.reader.app;

import com.amazonaws.services.rekognition.AmazonRekognition;
import com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public AmazonRekognition rekognitionClient(){
        return AmazonRekognitionClientBuilder.defaultClient();
    }

}
