/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package image.text.reader.app;

import image.text.reader.app.domain.ResultTextAws;
import image.text.reader.app.domain.TextExtractAws;
import image.text.reader.app.service.PdfService;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class ApplicationTest {

    @Autowired
    PdfService pdfService;

    @Test
    public void testPDF2() {
        ///tmp/scraper/71088 GG.pdf
        long start = System.nanoTime();
        ResultTextAws res = pdfService.getPages2PDF("/tmp/scrapers/71088 GG.pdf", "BILL OF LADING", "/tmp/scrapers/");
        System.out.println("============ IMAGES LOAD ON [" + res.getResultDoc() + "] ==================");
        System.out.println("============ BOLS NUMS ARE [" + res.getBolNums().toString() + "] ==================");
        long duration = (System.nanoTime() - start) / 1_000_000;
        System.out.println("Done in " + duration + " msecs");
    }

    @Test
    public void testPDF2pagenum() {
        ///tmp/scraper/71088 GG.pdf
        long start = System.nanoTime();
        TextExtractAws image = pdfService.textImageFromPdf("/tmp/scrapers/71088 GG.pdf", "BILL OF LADING", 12);
        System.out.println(image);
        long duration = (System.nanoTime() - start) / 1_000_000;
        System.out.println("Done in " + duration + " msecs");
    }
}
